### ISSUE TITLE
Flarum v0.1.0 开发路线图

### ISSUE THREAD

**Issue by justjavac** [justjavac/flarum#3]
English: https://github.com/flarum/core/issues/74

这是一份 Flarum 未来的发展路线，包括：
- 以后可能会更改的计划或待办事项
- 正式版的发布日期还没有确定
- 有其它功能需求吗？阅读 [FAQ](http://justjavac.gitbooks.io/flarum/content/preface/faq.html) 文档
## 总架构

下一个版本是 **version 0.1.0**。这将是可用于生产环境的第一个版本。然而，在随后发布的 0.x 版本中，我们会继续进行迭代，以提升扩展API的性能。

为此，我们将发布一系列的测试版。我们的重点是如下几点：
- [ ] 使安装程序更加稳定
- [ ] 整理 API 和 文档 flarum/core#246
- [ ] 提高测试覆盖率 flarum/core#245
- [x] 让所有的功能都可以翻译 flarum/core#267 flarum/core#266 flarum/core#265
- [ ] 提升性能 flarum/core#127
- [x] 提升错误处理 flarum/core#118
- [x] Anti-spam反垃圾工具 flarum/core#271
- [ ] 改进文本编辑器，增加格式按钮和全屏预览 flarum/core#309
- [ ] SEO flarum/core#189
- [ ] 添加一些还没有的管理员选项（如 Logo 上传，SMTP，SSL）
- [ ] 对系统核心以及捆绑的扩展进行改进
- [ ] 将 Likes 扩展并入到 "Rate" 扩展中 flarum/core#306
- [ ] 键盘快捷键 flarum/core#155
- [ ] 重写 Pusher 扩展 flarum/core#321
- [ ] 新扩展：Private Discussions, SSO, Reporting, Answers, Embed
### Core 核心
- [ ] 可以按“讨论标题”进行搜索 flarum/core#257
- [ ] 实现更多的高级搜索语法 flarum/core#256
- [ ] 让用户可以停用自己的账号，并销毁自己的信息 flarum/core#255
- [x] 增加在线用户状况 flarum/core#254
- [ ] 检测到用户已经登出时，提示用户重新输入密码 flarum/core#253
- [ ] 设计并实现密码重置页面和错误页面的 UI 设计 flarum/core#252
- [ ] 对 slug 进行音译 flarum/core#194
- [ ] 减少用户的操作行为 flarum/core#191
- [ ] 修改讨论的边栏 flarum/core#190
- [ ] SEO flarum/core#189
- [ ] 浮动讨论标题 flarum/core#157
- [ ] 键盘快捷键 flarum/core#155
- [ ] 讨论列表无限滚动 + 加载占位符 flarum/core#115
### 管理后台
- [x] 改善页面设计，允许上传 Logo flarum/core#268
- [x] 添加 SMTP 设置的页面 flarum/core#258
- [x] SSL 支持 flarum/core#167
- [ ] 允许 API 使用主密钥访问 flarum/core#205
### 安装程序
- [x] 完善的安装之前的系统需求检查
- [x] 输入验证
- [ ] 支持其它数据库
- [x] 支持数据表前缀 flarum/core#269
- [x] 支持安装在子目录 flarum/core#291
- [x] Web安装程序和命令行安装程序做相同的系统需求检查
### Mentions
- [x] 当选中文本后，弹出上下文菜单 flarum/core#320
### Subscriptions
- [x] 用户可以自己设置，是否自动订阅自己创建的或者回复过的讨论 flarum/core#310
### Suspend
- [ ] 当系统禁止或者恢复了某个用户时，通知该用户 flarum/core#322
### Likes
- [ ] 合并到 "Rate" 扩展 flarum/core#306
### Pusher
- [ ] 重写 flarum/core#321
### Tags
- [ ] Apply a className to various elements based on the active tags flarum/core#327
- [ ] Allow tags to have default sort orders flarum/core#328
- [ ] Add ability to style tags with background images flarum/core#329
- [ ] Add setting to allow discussion authors to edit tags flarum/core#330
### 新扩展
- [ ] Private Discussions
- [x] SSO
- [x] Reporting
- [ ] Answers
- [x] Embed
- [x] Header Links
## 愿望清单

这是我们一定要做的事情的清单，但是还未确定什么时候开始。
- 草稿
- RTL 支持
- 管理仪表盘 flarum/core#259
- 论坛的关于页面和其他静态页 flarum/core#134
- Extension Marketplace
- Easy upgrade process
- 迁移 (esoTalk, FluxBB, others)
- Laravel integration flarum/core#274

**Comment by emsdog** [comment]
the image upload function by client is very needed.

**Comment by justjavac** [comment]
@emsdog 会有相关插件

**Comment by hick** [comment]
@justjavac  一直关注, 楼上说的发帖的时候带图片, 好像看有用 flarum 的有实现了哈, 就是跟 github 类似, 在输入框 ctrl + v 就上传图片并插入 markdown 式的链接语法, 就是这个:  http://fo.szlt.net/d/3/56  只是不知道用的哪个插件, 好像那边你也是在下面有回 :) , 搜索找过好几个什么图片/媒体的, 看起来像用起来好像不是.

另外这个路线图没有时间计划, 不知道正式版大概啥时候出? 很想用这个在年前乃至新年那阵子搭建一个 Emacs 爱好者社区.

**Comment by justjavac** [comment]
@hick 那个是之前版本的插件，一直没有更新。

**Comment by eWeiMe** [comment]
不更新了？

**Comment by 54853315** [comment]
请问是否支持代码高亮？

**Comment by Lyken17** [comment]
@54853315 支持

**Comment by NCUTCodingMan** [comment]
安装flarum教程就有点小问题，标准的还是看官方API吧

**Comment by justjavac** [comment]
@NCUTCodingMan 中文版安装手册是beta4的，一直没有更新

**Comment by lizzca** [comment]
大大

**Comment by cskason** [comment]
已经不更新了吧？

**Comment by liran** [comment]
项目很好，不知道还更新？

**Comment by RockNHawk** [comment]
英文官网在更新 这个是别人的分支

**Comment by sunhai1988** [comment]
有支持汉化的吗

**Comment by tdqf** [comment]
项目很好 支持一下   下一步我打算用 [www.chao.ma](https://manman.qian.lu) 做一个 潮妈 社区

**Comment by GreenJoson** [comment]
请问,4年了....啥时候正式版,不会夭折了吧?

**Comment by BobLiu0518** [comment]
请问,4年了....啥时候正式版,不会夭折了吧?
